### ISSUE TITLE
add saturated image

### ISSUE THREAD

**Issue by laurenszlosek** [laurenszlosek/artGallery#1]
- [ ] add python script titled "toSaturated.py" 
- [ ] write script to saturate image
- [ ] add a before image to "galleryImages/beforeImages"
- [ ] use "toSaturated" to create an after image
- [ ] add before and after art to index.html

**Comment by vishnuteja94** [comment]
Hey Hi, working on this.

**Comment by laurenszlosek** [comment]
#8
